### ISSUE TITLE
Website Breaks in prod

### ISSUE THREAD

**Issue by vikingwarior** [adrianhajdin/iphone#20]
I tried to deploy the site through netifly and vercel, breaks in both cases with following error. Works as expected on local though

hook.js:608 Error: Could not load public/models/scene.glb: fetch for "https://iphone-website-swart.vercel.app/public/models/scene.glb" responded with 404: 
    at index-kjjZ4jMv.js:3953:24828
    at Object.l [as onError] (index-kjjZ4jMv.js:4071:16694)
    at index-kjjZ4jMv.js:123:125986

**Comment by vikingwarior** [comment]
@adrianhajdin can you help me out with the issue?

**Comment by vikingwarior** [comment]
Repo link: https://github.com/vikingwarior/iphone-website
